<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
  <!-- Please see https://github.com/pp-gps-p/Porkala-ortofoton-i-Guru-Maps -->
  <!-- This proxy will be available until September 2025-->
  <name>Porkala 1944</name>
  <url>http://52.57.84.58:8080/wmts/orto1944_EPSG3857/webmercator/{$z}/{$x}/{$y}.png</url>
  <minZoom>0</minZoom>
  <maxZoom>19</maxZoom>
  <tileSize>256</tileSize>
</customMapSource>
