<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
  <!-- Please see https://github.com/pp-gps-p/Porkala-orto-fotos-1956-in-Guru-Maps-proxy -->
  <!-- This proxy will at least be available until September 2025-->
  <name>Orto 1954 EPSG:3857</name>
  <url>http://52.57.84.58:8080/wmts/orto1954_EPSG3857/webmercator/{$z}/{$x}/{$y}.png</url>
  <minZoom>0</minZoom>
  <maxZoom>19</maxZoom>
  <tileSize>256</tileSize>
</customMapSource>
